"""guest checkout support

Revision ID: 88d695df7f88
Revises: 3ff78d5ca57d
Create Date: 2026-08-07 01:49:27.958497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d695df7f88'
down_revision: Union[str, Sequence[str], None] = '3ff78d5ca57d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('guest_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('guest_phone', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('guest_email', sa.String(), nullable=True))
    op.alter_column('orders', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('orders', 'guest_email')
    op.drop_column('orders', 'guest_phone')
    op.drop_column('orders', 'guest_name')
    # ### end Alembic commands ###
