"""Fix any errors

Revision ID: 9f25d17621e5
Revises: 043bf94f90e4
Create Date: 2026-07-11 02:16:58.539220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f25d17621e5'
down_revision: Union[str, Sequence[str], None] = '043bf94f90e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE TYPE userrole AS ENUM ('CUSTOMER', 'BARISTA', 'ADMIN')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('verification_tokens',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('token_type', sa.Enum('EMAIL_CONFIRMATION', 'PASSWORD_RESET', name='verificationtokentype'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_verification_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_tokens'))
    )
    op.create_index(op.f('ix_verification_tokens_id'), 'verification_tokens', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_order', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_id', sa.BIGINT(), nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_items_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.drop_index(op.f('ix_orderitems_id'), table_name='orderitems')
    op.drop_table('orderitems')
    op.add_column('tags', sa.Column('slug', sa.String(length=50), nullable=False))
    op.create_unique_constraint(op.f('uq_tags_slug'), 'tags', ['slug'])
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('CUSTOMER', 'BARISTA', 'ADMIN', name='userrole'), nullable=False))
    op.add_column('users', sa.Column('bonus_points', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_unique_constraint(op.f('uq_users_phone'), 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_phone'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'bonus_points')
    op.drop_column('users', 'role')
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'name')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    op.drop_constraint(op.f('uq_tags_slug'), 'tags', type_='unique')
    op.drop_column('tags', 'slug')
    op.create_table('orderitems',
    sa.Column('order_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_at_order', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_orderitems_order_id_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_orderitems_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orderitems'))
    )
    op.create_index(op.f('ix_orderitems_id'), 'orderitems', ['id'], unique=False)
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_verification_tokens_id'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
    op.execute("DROP TYPE userrole")
