"""add image_url to users

Revision ID: fa699b7ca917
Revises: c8d6529c2263
Create Date: 2026-07-30 18:15:58.409229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa699b7ca917'
down_revision: Union[str, Sequence[str], None] = 'c8d6529c2263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'price_at_order',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('users', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.alter_column('verification_tokens', 'token_type',
               existing_type=postgresql.ENUM('EMAIL_CONFIRMATION', 'PASSWORD_RESET', name='verificationtokentype'),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_tokens', 'token_type',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('EMAIL_CONFIRMATION', 'PASSWORD_RESET', name='verificationtokentype'),
               existing_nullable=False)
    op.drop_column('users', 'image_url')
    op.alter_column('products', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('order_items', 'price_at_order',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###
